
# Source: flightctl/templates/flightctl-api-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flightctl-api-config
  namespace: open-cluster-management
data:
  config.yaml: |-
    database:
        hostname: flightctl-db.open-cluster-management.svc.cluster.local
        type: pgsql
        port: 5432
        name: flightctl
    service:
        address: :3443
        agentEndpointAddress: :7443
        agentGrpcAddress: :7444
        httpReadTimeout: "5m"
        httpReadHeaderTimeout: "5m"
        httpWriteTimeout: "5m"
        httpMaxNumHeaders: 32
        httpMaxHeaderBytes: 33010
        httpMaxUrlLength: 2000
        httpMaxRequestSize: 53137200
        baseUrl: https://api.test/
        baseAgentEndpointUrl: https://agent-api.test/
        baseAgentGrpcUrl: grpcs://agent-grpc.test
        baseUIUrl: https://console-openshift-console.test/edge
        altNames:
          - api.test
          - agent-api.test
          - agent-grpc.test
          - flightctl-api
          - flightctl-api.open-cluster-management
          - flightctl-api.open-cluster-management.svc.cluster.local
          - flightctl-api-agent-grpc
          - flightctl-api-agent-grpc.open-cluster-management
          - flightctl-api-agent-grpc.open-cluster-management.svc.cluster.local
    kv:
        hostname: flightctl-kv.open-cluster-management.svc.cluster.local
        port: 6379
    auth:
        insecureSkipTlsVerify: false
        caCert: 
        k8s:
            apiUrl: https://kubernetes.default.svc
            externalOpenShiftApiUrl: test
            rbacNs: open-cluster-management
