apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flightctl-viewer
  namespace: '{{ default "default" .Values.global.namespace }}'
rules:
- apiGroups:
  - flightctl.io
  resources:
  - devices
  - fleets
  - resourcesyncs
  verbs:
  - get
  - list
