
# Source: flightctl/templates/flightctl-api-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flightctl-api-config
  namespace: {{ .Values.global.namespace }}
data:
  config.yaml: |-
    database:
        hostname: flightctl-db.{{ .Values.global.namespace }}.svc.cluster.local
        type: pgsql
        port: 5432
        name: flightctl
    service:
        address: :3443
        agentEndpointAddress: :7443
        agentGrpcAddress: :7444
        httpReadTimeout: "5m"
        httpReadHeaderTimeout: "5m"
        httpWriteTimeout: "5m"
        httpMaxNumHeaders: 32
        httpMaxHeaderBytes: 33010
        httpMaxUrlLength: 2000
        httpMaxRequestSize: 53137200
        baseUrl: https://api.{{ .Values.global.baseDomain}}/
        baseAgentEndpointUrl: https://agent-api.{{ .Values.global.baseDomain}}/
        baseAgentGrpcUrl: grpcs://agent-grpc.{{ .Values.global.baseDomain}}
        baseUIUrl: https://console-openshift-console.{{ .Values.global.baseDomain}}/edge
        altNames:
          - api.{{ .Values.global.baseDomain}}
          - agent-api.{{ .Values.global.baseDomain}}
          - agent-grpc.{{ .Values.global.baseDomain}}
          - flightctl-api
          - flightctl-api.{{ .Values.global.namespace }}
          - flightctl-api.{{ .Values.global.namespace }}.svc.cluster.local
          - flightctl-api-agent-grpc
          - flightctl-api-agent-grpc.{{ .Values.global.namespace }}
          - flightctl-api-agent-grpc.{{ .Values.global.namespace }}.svc.cluster.local
    kv:
        hostname: flightctl-kv.{{ .Values.global.namespace }}.svc.cluster.local
        port: 6379
    auth:
        insecureSkipTlsVerify: false
        caCert: 
        k8s:
            apiUrl: https://kubernetes.{{ .Values.global.namespace }}.svc
            externalOpenShiftApiUrl: {{ .Values.global.aPIUrl}}
            rbacNs: {{ .Values.global.namespace }}
