apiVersion: v1
data:
  password: VXM2NG0tR0pJUTMtYnpITlQtRzZUVlg=
kind: Secret
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: flightctl-kv-secret
  namespace: '{{ default "default" .Values.global.namespace }}'
type: Opaque
