
# Source: flightctl/templates/flightctl-periodic-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flightctl-periodic-config
  namespace: default
data:
  config.yaml: |-
    database:
        hostname: flightctl-db.default.svc.cluster.local
        type: pgsql
        port: 5432
        name: flightctl
    service: {}
    kv:
        hostname: flightctl-kv.default.svc.cluster.local
        port: 6379
