apiVersion: v1
data:
  masterPassword: SXkySFItMlVrRTAtSTBDT1ItZkNyVWI=
  masterUser: YWRtaW4=
  password: VndSUXctejZMYlYtYjVpdG4tVVB2M2E=
  user: ZGVtb3VzZXI=
  userPassword: UEFodHEtdkNQRkMtcFJQYTgtNDdmRms=
kind: Secret
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: flightctl-db-secret
  namespace: '{{ .Values.global.namespace }}'
type: Opaque
