
# Source: flightctl/templates/flightctl-periodic-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flightctl-periodic-config
  namespace: open-cluster-management
data:
  config.yaml: |-
    database:
        hostname: flightctl-db.open-cluster-management.svc.cluster.local
        type: pgsql
        port: 5432
        name: flightctl
    service: {}
    kv:
        hostname: flightctl-kv.open-cluster-management.svc.cluster.local
        port: 6379
