apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: multiclusterhub-operator
  name: mch-auth-proxy-metrics-service
spec:
  ports:
  - name: https
    port: 9443
    targetPort: https
  selector:
    control-plane: multiclusterhub-operator
status:
  loadBalancer: {}
