# Copyright Contributors to the Open Cluster Management project

resources:
- manifests.yaml
- service.yaml

namespace: open-cluster-management
namePrefix: multiclusterhub-
configurations:
- kustomizeconfig.yaml

patchesStrategicMerge:
- patch_annotation.yaml
