# Copyright Contributors to the Open Cluster Management project


apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
  - clientConfig:
      service:
        name: multiclusterhub-operator-webhook
        namespace: system
        path: /validate-v1-multiclusterhub
