# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mch-auth-proxy-metrics-reader
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
