apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: multiclusterhub-operator
  name: mch-auth-proxy-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 9443
    targetPort: https
  selector:
    control-plane: multiclusterhub-operator
