# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mch-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mch-leader-election-role
subjects:
- kind: ServiceAccount
  name: multiclusterhub-operator
  namespace: system
