apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: multiclusterhub-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MultiClusterHub defines the configuration for an instance of the
        MultiCluster Hub
      displayName: MultiClusterHub
      kind: MultiClusterHub
      name: multiclusterhubs.operator.open-cluster-management.io
      specDescriptors:
      - description: 'Specifies deployment replication for improved availability.
          Options are: Basic and High (default)'
        displayName: Availability Configuration
        path: availabilityConfig
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:select:High
        - urn:alm:descriptor:com.tectonic.ui:select:Basic
      - description: Provide the customized OpenShift default ingress CA certificate
          to RHACM
        displayName: Custom CA Configmap
        path: customCAConfigmap
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:io.kubernetes:ConfigMap
      - description: Disable automatic import of the hub cluster as a managed cluster
        displayName: Disable Hub Self Management
        path: disableHubSelfManagement
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:io.kubernetes:booleanSwitch
      - description: Disable automatic update of ClusterImageSets
        displayName: Disable Update ClusterImageSet
        path: disableUpdateClusterImageSets
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:io.kubernetes:booleanSwitch
      - description: (Deprecated) Overrides for the default HiveConfig spec
        displayName: Hive Config
        path: hive
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: Override pull secret for accessing MultiClusterHub operand and
          endpoint images
        displayName: Image Pull Secret
        path: imagePullSecret
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:Secret
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: Configuration options for ingress management
        displayName: Ingress Management
        path: ingress
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: Developer Overrides
        displayName: Developer Overrides
        path: overrides
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:hidden
      - description: (Deprecated) Install cert-manager into its own namespace
        displayName: Separate Certificate Management
        path: separateCertificateManagement
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      version: v1
  description: 'The Open Cluster Management Hub operator installs and maintains an
    instance of the OCM hub, a central management console for managing OpenShift and
    Kubernetes clusters. '
  displayName: Open Cluster Management Hub
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - multiclusterhub
  - install
  links:
  - name: Multiclusterhub Operator
    url: https://multiclusterhub-operator.domain
  maintainers:
  - email: ocm-dev@open-cluster-management.io
    name: Open Cluster Management Project team
  maturity: alpha
  provider:
    name: Redhat
  version: 0.0.0
