# Copyright Contributors to the Open Cluster Management project

# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: multiclusterhubs.operator.open-cluster-management.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: system
          name: multiclusterhub-operator-webhook
          path: /convert
      conversionReviewVersions:
      - v1
